name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ develop, main ]

env:
  DOCKER_IMAGE: bwbohl/sencha-cmd

jobs:

  build:
    name: Build Edirom Online
    runs-on: ubuntu-latest

    steps:
    - name: Chekout repository
      uses: actions/checkout@v4
      
    - name: Get short sha
      uses: benjlevesque/short-sha@v2.2
      id: short-sha
      with:
        length: 7       

    - name: Build Edirom Online from ${{ github.ref }} at ${{ github.sha }}
      run: docker run --rm -v $(pwd):/app -w /app --entrypoint ./build.sh bwbohl/sencha-cmd

    - name: Upload Artifacts to action run
      if: github.repository == 'Edirom/Edirom-Online'
      uses: actions/upload-artifact@v3.1.3
      with:
        # The name that the artifact will be made available under
        name: EdiromOnline_${{ steps.short-sha.outputs.sha }}.zip
        # The path to retrieve the artifact
        path: ${{ github.workspace }}/build-xar/Edirom-Online-*.xar
        if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn` 
        #optional retention-days: 1 to 90
