name: Deploy gh-pages Docker Image

on:
  push:
    branches: [gh-pages]

permissions:
  contents: read
  packages: write

concurrency:
  group: deploy-gh-pages
  cancel-in-progress: false

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/edirom/edirom-online
          tags: |
            type=raw,value=gh-pages
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Trigger Keel deploy
        run: |
          curl -X POST https://keel1.edirom.de/v1/webhooks/native \
            -H 'Content-Type: application/json' \
            -d '{"name":"ghcr.io/edirom/edirom-online","tag":"gh-pages"}'
