# Adapted from https://github.com/fair-software/howfairis-github-action
# License: Apache License 2.0

name: fair-software

# This workflow is triggered on pushes to the main branch and on tags starting with 'v'.
on: 
  push:
    branches:
      - main
      - 'release/**'
    tags:
      - 'v*'

jobs:
  verify:
    name: "fair-software"
    runs-on: ubuntu-latest
    steps:
      - uses: fair-software/howfairis-github-action@0.2.1
        name: Measure compliance with fair-software.eu recommendations
        env:
          PYCHARM_HOSTED: "Trick colorama into displaying colored output" 
          APIKEY_GITHUB: "${{ github.actor }}:${{ secrets.VIFEBOTS_GITHUB_TOKEN }}"
        with:
          MY_REPO_URL: "https://github.com/${{ github.repository }}"
